# Generated by Django 3.2 on 2024-02-08 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='inclusions',
        ),
        migrations.AlterField(
            model_name='traveler',
            name='gender',
            field=models.CharField(choices=[['MALE', 'Male'], ['FEMALE', 'Female']], max_length=10, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[['MALE', 'Male'], ['FEMALE', 'Female']], max_length=10, verbose_name='gender'),
        ),
    ]
